-- Create user_preferences table if it doesn't exist
create table if not exists public.user_preferences (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid references auth.users(id) on delete cascade,
  purpose text not null,
  selected boolean default true,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint user_preferences_user_id_purpose_key unique (user_id, purpose),
  constraint user_preferences_user_id_fkey foreign key (user_id) references auth.users(id) ON DELETE CASCADE
);

-- Set up Row Level Security (RLS)
alter table public.user_preferences enable row level security;

-- Create policies for user_preferences table
create policy "Users can view their own preferences." on user_preferences
  for select using (auth.uid() = user_id);

create policy "Users can insert their own preferences." on user_preferences
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own preferences." on user_preferences
  for update using (auth.uid() = user_id);